var previewTpl = [
	'<table class = "myTable">',
		'<tr>',
		'    <td>',
		'        Имя:',
		'    </td>',
		'    <td>',
		'        <%= lastName%>',
		'        <%= name%>',
		'        <%= secondName%>',
		'    </td>',
		'</tr>',
		'<tr>',
		'    <td>',
		'        Возраст:',
		'    </td>',
		'    <td>',
		'        <%= age%>',
		'    </td>',
		'</tr>',
		'<tr>',
		'    <td>',
		'        Пол:',
		'    </td>',
		'    <td>',
		'        <%= gender%>',
		'    </td>',
		'</tr>',
		'<tr>',
		'    <td>',
		'        Пасспорт:',
		'    </td>',
		'    <td>',
		'        <%= passportData%>',
		'    </td>',
		'</tr>',
		'<tr>',
		'    <td>',
		'        Индификационный номер:',
		'    </td>',
		'    <td>',
		'        <%= idCode%>',
		'    </td>',
		'</tr>',
	'</table>',
	'<button id = closePreview>',
		'Закрыть',
	'</button>'].join('');
