viewTpl = [
'	<div class = "fullName hidden">',
'		<table class = "myTable" >',
'			<tr>',
'				<td>',
'					Фалимия имя отчество:',
'				</td>',
'				<td>',
'					<%= lastName %>',
'					<%= name %>',
'					<%= secondName %>',
'				</td>',
'			</tr>',
'		</table>',
'	</div>',
'	<div class = "ageGender hidden">',
'		<table class = "myTable">',
'			<tr>',
'				<td>',
'					Возраст:',
'				</td>',
'				<td>',
'					<%= age %>',
'				</td>',
'			</tr>',
'			<tr>',
'				<td>',
'					Пол:',
'				</td>',
'				<td>',
'					<%= gender %>',
'				</td>',
'			</tr>',
'		</table>',
'	</div>',
'	<div class = "passportData hidden">',
'		<table class = "myTable">',
'			<tr>',
'				<td>',
'					Паспортные данные:',
'				</td>',
'				<td>',
'					<%= passportData %>',
'				</td>',
'			</tr>',
'			<tr>',
'				<td>',
'					Идентификацилнный код:',
'				</td>',
'				<td>',
'					<%= idCode %>',
'				</td>',
'			</tr>',
'		</table>',
'	</div>'
].join('');