viewPassportTpl = [
'	<tr>',
'		<td>',
'			Паспортные данные:',
'		</td>',
'		<td>',
'			<%= passportData %>',
'		</td>',
'	</tr>',
'	<tr>',
'		<td>',
'			Идентификацилнный код:',
'		</td>',
'		<td>',
'			<%= idCode %>',
'		</td>',
'	</tr>',
].join('');