viewPassportTpl = [
'<table class = "myTable">',
'	<tr>',
'		<td>',
'			Паспортные данные:',
'		</td>',
'		<td>',
'			<%= passportData %>',
'		</td>',
'	</tr>',
'	<tr>',
'		<td>',
'			Идентификацилнный код:',
'		</td>',
'		<td>',
'			<%= idCode %>',
'		</td>',
'	</tr>',
'</table>'].join('');